-- CineAI - Supabase/Postgres schema
-- Run this in Supabase Dashboard > SQL Editor.
-- This project uses its own FastAPI auth, not Supabase Auth.

begin;

create table if not exists public.users (
    id integer generated by default as identity primary key,
    email varchar(255) not null,
    username varchar(100) not null,
    hashed_password varchar(255) not null,
    is_admin boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    content_type varchar(10) not null default '',
    genres_include text not null default '',
    genres_exclude text not null default '',
    duration_pref varchar(20) not null default 'Qualquer',
    weight_rating double precision not null default 0.8,
    weight_popularity double precision not null default 0.8,
    prefer_new boolean not null default false,
    classic_focus boolean not null default false,
    keywords text,
    actor varchar(200),
    director varchar(200),
    company varchar(200),
    network varchar(200),
    year integer,
    min_vote double precision,
    updated_at timestamptz not null default now()
);

create table if not exists public.recommendation_history (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    tmdb_id integer not null,
    content_type varchar(10) not null,
    title varchar(500) not null,
    genres text not null default '',
    vote_avg double precision not null default 0.0,
    popularity double precision not null default 0.0,
    year integer,
    score double precision not null default 0.0,
    rank integer not null default 1,
    search_mode varchar(20) not null default 'normal',
    recommended_at timestamptz not null default now()
);

create unique index if not exists ix_users_email on public.users(email);
create unique index if not exists ix_users_username on public.users(username);

create index if not exists ix_user_preferences_user_id on public.user_preferences(user_id);
create unique index if not exists ux_user_preferences_user_id on public.user_preferences(user_id);

create index if not exists ix_recommendation_history_user_id on public.recommendation_history(user_id);
create index if not exists ix_recommendation_history_tmdb_id on public.recommendation_history(tmdb_id);
create index if not exists ix_recommendation_history_recommended_at on public.recommendation_history(recommended_at);
create index if not exists ix_recommendation_history_search_mode on public.recommendation_history(search_mode);

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_users_username_length'
        and conrelid = 'public.users'::regclass
    ) then
        alter table public.users
        add constraint ck_users_username_length
        check (char_length(username) between 3 and 100);
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_user_preferences_content_type'
        and conrelid = 'public.user_preferences'::regclass
    ) then
        alter table public.user_preferences
        add constraint ck_user_preferences_content_type
        check (content_type in ('', 'movie', 'tv'));
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_user_preferences_duration_pref'
        and conrelid = 'public.user_preferences'::regclass
    ) then
        alter table public.user_preferences
        add constraint ck_user_preferences_duration_pref
        check (duration_pref in ('Qualquer', 'Curta', 'Média', 'Longa'));
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_user_preferences_weights'
        and conrelid = 'public.user_preferences'::regclass
    ) then
        alter table public.user_preferences
        add constraint ck_user_preferences_weights
        check (
            weight_rating between 0 and 1
            and weight_popularity between 0 and 1
        );
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_recommendation_history_content_type'
        and conrelid = 'public.recommendation_history'::regclass
    ) then
        alter table public.recommendation_history
        add constraint ck_recommendation_history_content_type
        check (content_type in ('movie', 'tv'));
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_recommendation_history_rank'
        and conrelid = 'public.recommendation_history'::regclass
    ) then
        alter table public.recommendation_history
        add constraint ck_recommendation_history_rank
        check (rank between 1 and 3);
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_recommendation_history_search_mode'
        and conrelid = 'public.recommendation_history'::regclass
    ) then
        alter table public.recommendation_history
        add constraint ck_recommendation_history_search_mode
        check (search_mode in ('normal', 'specific'));
    end if;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_user_preferences_updated_at on public.user_preferences;
create trigger trg_user_preferences_updated_at
before update on public.user_preferences
for each row
execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.user_preferences enable row level security;
alter table public.recommendation_history enable row level security;

commit;

-- After creating your account through the app, make yourself admin if needed:
-- update public.users set is_admin = true where email = 'seu@email.com';
